#include "hal_data.h"
#include "hal_entry.h"
#include "uart_ep.h"
#include "stdio.h"
#include "common_utils.h"
#include "i2c_controller.h"
#include "mipi_dsi_ep.h"
#include "lontium_bridge_lt8912.h"


int  __weak _write(int file, char *ptr, int len){
   (void)file;

   uart_print_user_msg((uint8_t *)ptr);

   return len;
}


/*******************************************************************************************************************//**
 * main() is generated by the RA Configuration editor and is used to generate threads if an RTOS is used.  This function
 * is called by main() when no RTOS is used.
 **********************************************************************************************************************/
void hal_entry(void)
{
    /* TODO: add your own code here */

    fsp_err_t err = FSP_SUCCESS;

    uart_initialize();
    R_IIC_MASTER_Open(&g_i2c_master0_ctrl, &g_i2c_master0_cfg);


#if BSP_TZ_SECURE_BUILD
    /* Enter non-secure code */
    R_BSP_NonSecureEnter();
#endif
    R_BSP_PinAccessEnable();
    R_BSP_PinWrite(RESET_N, BSP_IO_LEVEL_HIGH);
    R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MILLISECONDS);
    R_BSP_PinWrite(RESET_N, BSP_IO_LEVEL_LOW);
    R_BSP_SoftwareDelay(5, BSP_DELAY_UNITS_MILLISECONDS);
    R_BSP_PinWrite(RESET_N, BSP_IO_LEVEL_HIGH);
    R_BSP_SoftwareDelay(100, BSP_DELAY_UNITS_MILLISECONDS);

    R_BSP_PinWrite(BACKLIGHT, BSP_IO_LEVEL_HIGH);

    R_BSP_PinWrite(DSI_DEST_SELECT, BSP_IO_LEVEL_LOW);

//    LT8912B_Config();
//    pattern_test();
    HDMI_Test_Pattern();
//    mipi_dsi_entry();


   for(;;){


       printf("Deus é o Rei\r\n");
    //   R_IOPORT_PinWrite(&g_ioport_ctrl, MIPI_SELECT, BSP_IO_LEVEL_LOW);
     //  R_BSP_PinWrite(MIPI_SELECT, BSP_IO_LEVEL_LOW);
    //   R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);
     //  R_IOPORT_PinWrite(&g_ioport_ctrl, MIPI_SELECT, BSP_IO_LEVEL_HIGH);
    //   R_BSP_PinWrite(MIPI_SELECT, BSP_IO_LEVEL_HIGH);
       R_BSP_SoftwareDelay(200, BSP_DELAY_UNITS_MILLISECONDS);

   }
}



#if BSP_TZ_SECURE_BUILD

FSP_CPP_HEADER
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ();

/* Trustzone Secure Projects require at least one nonsecure callable function in order to build (Remove this if it is not required to build). */
BSP_CMSE_NONSECURE_ENTRY void template_nonsecure_callable ()
{

}
FSP_CPP_FOOTER

#endif
